---
- name: Install zsh
  hosts: all
  remote_user: james 
  tasks:
  - name: Install prerequisites
    become: yes
    apt:
        name: "{{ packages }}"
    vars:
        packages:
            - git
            - curl
            - wget
  - name: Install zsh
    become: yes
    apt:
        name: zsh
        update_cache: yes
  - name: Install Oh-My-zsh
    shell: zsh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  - name: Install custom settings for zsh
    get_url:
        url: https://raw.githubusercontent.com/JamieSinn/zsh/master/.zshrc
        dest: /home/james/.zshrc
        force: yes

